### ISSUE TITLE
Vendedor Eduardo Arinez - Pedido #38 - SATELITE-0002

### ISSUE THREAD

**Issue by xaviflores21** [DHM-DISTRIBUIDORA/.github#2]
El vendedor solo registro un pedido con valor de 114bs 
![image](https://github.com/DHM-DISTRIBUIDORA/.github/assets/17733377/323cc7c3-c085-4bf1-bdca-a31effc7fa37)
![image](https://github.com/DHM-DISTRIBUIDORA/.github/assets/17733377/44c92fe3-8587-418d-9b75-d757eac1dc38)

Pero al momento de imprimir su boleta, le aparece pedidos que no han sido registrados.
![image](https://github.com/DHM-DISTRIBUIDORA/.github/assets/17733377/7655a0b5-eb85-431b-86dd-3fb684bc7904)

**Comment by ruddypazd** [comment]
Description del error:

El error sucedió cuando el vendedor A intento registrar un pedido con 12 detalles, Este pedido (17223) fallo al registrar la cabecera por que el campo vobs tiene como limite de caracteres (75).

Luego el vendedor B registro el pedido y le asigno el mismo id de el anterior pedido (17223).




El problema fue que el detalle del pedido en la base de datos solo permite 75 caracteres y el usuario colocó mas.

Como podemos observer el error mas abajo nos dice que el `vobs` es `SAPP - Selecto a 89,borracho y maleta a 67,megarrollo a 21,50,  maleton a 75 megaceleste a 18,1x50 a 36,50, naranja a 44`, esta cadena tiene 120 caracteres de longitud. 


![WhatsApp Image 2024-02-16 at 12 04 11 AM](https://github.com/DHM-DISTRIBUIDORA/.github/assets/7370358/88b80464-0178-480d-9b3d-a9e97a171b8b)

```bash
[Thu Feb 15 09:29:57 BOT 2024] http-server --> dm_cabfac save 
SET DATEFORMAT 'YMD'; update dm_cabfac set vlongitud = -63.25006866455078,vhora = '1900-01-01 09:16:24.0',vlatitud = -17.33431053161621,direccion = 'Frente al merc. VILLA VERDE',vtipa = 0,vzona = 'MONTERO',clicod = 'MONTERO-0909',vdes = '0',codvendedor = 'V006',razonsocial = 'VENTAS MENORES DEL DIA',vpla = 0,nit = '99003',tipocliente = 'MINORISTA',vfec = '2024-02-15 00:00:00.0',telefonos = '+591 null',vobs = 'SAPP - Selecto a 89,borracho y maleta a 67,megarrollo a 21,50,  maleton a 75 megaceleste a 18,1x50 a 36,50, naranja a 44',nombrecliente = 'HELENA AISA',vtipo = '1' where idven = '17223'
java.lang.Exception: Los datos de cadena o binarios se truncarían.
        at Component.Http.send_(Http.java:117)
        at Component.Dhm.editar(Dhm.java:899)
        at Component.DmCabFac.save(DmCabFac.java:488)
        at Component.DmCabFac.onMessage(DmCabFac.java:38)
        at Manejador.onMessage(Manejador.java:35)
        at _component._Manejador.factory(_Manejador.java:28)
        at ServerHttp.Api.POST(Api.java:29)
        at org.jboss.com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:78)
        at org.jboss.sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:80)
        at org.jboss.com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:81)
        at org.jboss.sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:710)
        at org.jboss.com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:78)
        at org.jboss.sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:682)
        at org.jboss.sun.net.httpserver.ServerImpl$DefaultExecutor.execute(ServerImpl.java:202)
        at org.jboss.sun.net.httpserver.ServerImpl$Dispatcher.handle(ServerImpl.java:468)
        at org.jboss.sun.net.httpserver.ServerImpl$Dispatcher.run(ServerImpl.java:433)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

Al hacer esto el detalle se registraba pero no se registraba la cabecera, iba acumulando detalles y cuando inserto una observacion corta, todo el detalle acumulado se fue a al pedido exitoso.


Para resolver este problema lo hicimos desde frontend y backend:

- En el banckend se cambio para que si falla el pedido de error y no acumule el detalle.
- En el frontend se cambio el input detalle para que solo acepte < 65 caracteres.

 cambiamos para que cuando falle no acumule el detalle

**Comment by ruddypazd** [comment]
@xaviflores21 este Issue tiene un label de Corregido, la unica persona que cerrará los issues sos vos, cuando est6es seguro que se corrigio correctamente.

Saludos

**Comment by xaviflores21** [comment]
validacion descripcion corregida!!
